title: XRobot Doc
description: XRobot Doc

url: https://xrobot-org.github.io/

logo: "img/XRobot.png"

favicon_ico: "img/XRobot.jpeg"


aux_links:
  Github: https://github.com/xrobot-org/XRobot
  Gitee: https://gitee.com/x-robot/XRobot

plugins:
  - jekyll-remote-theme

remote_theme: https://github.com/just-the-docs/just-the-docs
